# Default values for Azure Policy Add-on on Azure Arc enabled Kubernetes clusters
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Microsoft Azure Policy Add-on on Azure Arc enabled Kubernetes clusters
azurepolicy:
  image:
    name: "mcr.microsoft.com/azure-policy/policy-kubernetes-addon-prod"
    tag: "prod_20200519.1"
## Replace <your_resource_id> with your Azure Arc enabled Kubernetes cluster resource Id. For example: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/testRG/Microsoft.Kubernetes/connectedClusters/testCluster
## Replace <your_client_id> with app Id of the service principal created for Azure Policy Add-on to communicate to Azure Policy service.
## Replace <your_client_secret> with password of the service principal created for Azure Policy Add-on to communicate to Azure Policy service.
## Replace <your_tenant_id> with tenant of the service principal created for Azure Policy Add-on to communicate to Azure Policy service.
  env:
    resourceid: <your_resource_id>
    clientid: <your_client_id>
    clientsecret: <your_client_secret>
    tenantid: <your_tenant_id>

## Microsoft Azure Policy Webhook
azurepolicywebhook:
  image:
    name: "mcr.microsoft.com/azure-policy/policy-kubernetes-webhook"
    tag: "prod_20200505.3"

## OPA Gatekeeper for Kubernetes clusters
gatekeeper:
  image:
    name: "openpolicyagent/gatekeeper"
    tag: "v3.1.0-beta.10"
  args:
    auditIntervalSeconds: 60
    constraintViolationsLimit: 100
  resources:
    cpuLimit: 1000m
    memoryLimit: 512Mi
    cpuRequests: 100m
    memoryRequests: 256Mi

## Alpine image used in the helm hook
alpine:
  image:
    name: "mcr.microsoft.com/azure-policy/alpine"
    tag: "prod_20200505.1"
